version: '3'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wvdashboard
    build: ./db
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
    restart: always
  hobo:
    build: ./hobo
    links:
      - db
    restart: always
  web:
    build: ./web
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - "8086:80"
    links:
     - db
    restart: always
