version: '2'
services:
  db:
    ports:
      - "5432:5432"
  web:
    command: [grunt]
    environment:
      - NODE_ENV=development_docker
    ports:
      - "35729:35729"
    volumes:
      - ./dev:/usr/src/app