version: '2'
services:
  db:
    ports:
      - "5432:5432"
  web:
    command: [grunt]
    environment:
      - NODE_ENV=development_docker
    ports:
      - "35729:35729"
    volumes:
      - ./web:/usr/src/app
      # don't overwrite dependencies
      - /usr/src/app/node_modules 
      - /usr/src/app/public/lib