version: '2'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=feed
    build: ./db
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
  hobo:
    build: ./hobo
    links:
      - db
  twitter:
    build: ./twitter
    links:
      - db
  web:
    build: ./web
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    links:
     - db
