version: '2'
services:
  bot:
    build: ./bot
    links:
      - db
  db:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=feed
    image: postgres
    volumes:
      - ./schema:/docker-entrypoint-initdb.d/
      - ./data:/var/lib/postgresql/data
  tasks:
    build: ./tasks
    links:
      - db
  web:
    build: ./web
    environment:
      - NODE_ENV=docker
    ports:
      - "3000:3000"
    links:
     - db
